package main

import (
	client "github.com/Clever/catapult/gen-go/client"
	v9 "github.com/Clever/wag/clientconfig/v9"
	trace "go.opentelemetry.io/otel/sdk/trace"
	tracetest "go.opentelemetry.io/otel/sdk/trace/tracetest"
	"log"
	"os"
)

// Code generated by launch-gen DO NOT EDIT.

// LaunchConfig is auto-generated based on the launch YML file
type LaunchConfig struct {
	Deps Dependencies
	Env  Environment
	AwsResources
	ExternalUrlUsage
}

// Dependencies has clients for the service's dependencies
type Dependencies struct {
	Catapult client.Client
}

// Environment has environment variables and their values
type Environment struct {
	FlareChannelPrefix  string
	JiraOrigin          string
	JiraUsername        string
	JiraPassword        string
	JiraProjectID       string
	SlackBotToken       string
	ChannelAgeThreshold string
	DryRun              string
}

// AwsResources contains string IDs that will help for accessing various AWS resources
type AwsResources struct{}

// ExternalUrlUsage uses discovery to generate urls for external services
type ExternalUrlUsage struct{}

// InitLaunchConfig creates a LaunchConfig
func InitLaunchConfig(exp *trace.SpanExporter) LaunchConfig {
	var exporter trace.SpanExporter
	if exp == nil {
		exporter = tracetest.NewNoopExporter()
	} else {
		exporter = *exp
	}
	catapult, err := client.NewFromDiscovery(v9.WithTracing("catapult", exporter))
	if err != nil {
		log.Fatalf("discovery error: %s", err)
	}
	return LaunchConfig{
		AwsResources: AwsResources{},
		Deps:         Dependencies{Catapult: catapult},
		Env: Environment{
			ChannelAgeThreshold: requireEnvVar("CHANNEL_AGE_THRESHOLD"),
			DryRun:              requireEnvVar("DRY_RUN"),
			FlareChannelPrefix:  requireEnvVar("FLARE_CHANNEL_PREFIX"),
			JiraOrigin:          requireEnvVar("JIRA_ORIGIN"),
			JiraPassword:        requireEnvVar("JIRA_PASSWORD"),
			JiraProjectID:       requireEnvVar("JIRA_PROJECT_ID"),
			JiraUsername:        requireEnvVar("JIRA_USERNAME"),
			SlackBotToken:       requireEnvVar("SLACK_BOT_TOKEN"),
		},
		ExternalUrlUsage: ExternalUrlUsage{},
	}
}

// requireEnvVar exits the program immediately if an env var is not set
func requireEnvVar(s string) string {
	val, present := os.LookupEnv(s)
	if !present {
		log.Fatalf("env var %s is not defined", s)
	}
	return val
}

// getS3NameByEnv adds "-dev" to an env var name unless we're in "production" deploy env
// We check both DEPLOY_ENV and _DEPLOY_ENV env vars, which are injected by our deployment system for Lambda and non-Lambda deployments, respectively
func getS3NameByEnv(s string) string {
	env := os.Getenv("DEPLOY_ENV")
	if env == "" {
		env = os.Getenv("_DEPLOY_ENV")
	}
	if env == "" {
		log.Fatal("Unable to determine deployment environment (DEPLOY_ENV and _DEPLOY_ENV are undefined)")
	}
	if env == "production" {
		return s
	}
	return s + "-dev"
}
